name: manage-azure-policy-ddb3a330
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'VMDiag/policies/Deploy_Diagnostic_Settings_for_Virtual_Machines_to_Log_Analytics_workspace_Deploy-Diagnostics-VM/**'
#      - .github/workflows/manage-azure-policy-ddb3a330.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_ddb3a330}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          VMDiag/policies/Deploy_Diagnostic_Settings_for_Virtual_Machines_to_Log_Analytics_workspace_Deploy-Diagnostics-VM/**
